apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms1
  namespace: default
  labels:
    app: ms1
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
      - image: agustincharry/ms1:1.1
        name: ms1
        ports:
        - name: http
          containerPort: 4000