kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: ms1-lb
  labels:
    app: deployment_label
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myLB
    spec:
      containers:
      - image: agustincharry/ms1:1.2
        name: ms1
        ports:
        - name: http
          containerPort: 4000