apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1
  labels:
    app: ms1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
      - image: agustincharry/ms1:1.2
        name: ms1
        ports:
        - name: http
          containerPort: 4000
        livenessProbe:
          httpGet:
            path: /
            port: 4000
        readinessProbe:
          httpGet:
            path: /
            port: 4000