apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-lb
  labels:
    app: deployment_label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myLB
  template:
    metadata:
      labels:
        app: myLB
    spec:
      containers:
      - image: agustincharry/ms1:1.2
        name: ms1
        ports:
        - name: http
          containerPort: 4000