apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms2-lb
  namespace: default
  labels:
    app: deployment_label
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: myLB
    spec:
      containers:
      - image: agustincharry/ms2:1.2
        name: ms2
        ports:
        - name: http
          containerPort: 4000