apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: ms2
  labels:
    app: ms2
spec:
  revisionHistoryLimit: 2
  strategy:
    type: Rolling
  replicas: 1
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
      - image: agustincharry/ms2:1.2
        name: ms2
        ports:
        - name: http
          containerPort: 4000